[package]
edition = "2021"
name = "tesseract-static"
version = "0.2.1"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]
build = "build.rs"
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false
description = "Tesseract + leptonica bindings for lightshotv2 (trimmed)"
license = "Apache-2.0"

[lib]
name = "tesseract_static"
path = "src/lib.rs"

[dependencies.dlopen]
version = "0.1.8"

[dependencies.lazy_static]
version = "1.5.0"

[dependencies.thiserror]
version = "2.0.11"

[features]
default = []
