[package]
name = "lucentshot"
version = "1.0.3"
edition = "2021"
description = "A fast Windows screenshot tool"
build = "build.rs"

[package.metadata.winres]
FileDescription = "LucentShot - Screenshot tool"
ProductName = "LucentShot"
CompanyName = "Dvow"
OriginalFilename = "lucentshot.exe"
LegalCopyright = "Copyright (C) 2026"

[features]
default = ["ocr"]
ocr = ["dep:dlopen", "dep:tts"]

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = "z"
debug = false

[dependencies]
arboard = "3.4"
eframe = { version = "0.34", default-features = false, features = ["default_fonts", "glow"] }
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "bmp", "gif", "ico"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "multipart", "blocking", "native-tls"] }
rfd = { version = "0.15", default-features = false }
webbrowser = "1.0"
anyhow = "1.0"
ab_glyph = "0.2"
imageproc = { version = "0.24", default-features = false }
serde_json = "1.0"
tiny-skia = "0.11"
resvg = { version = "0.45", default-features = false }
tray-icon = { version = "0.14", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
dlopen = { version = "0.1.8", optional = true }
tts = { version = "0.26", default-features = false, optional = true }
dirs = "5.0"
windows = { version = "0.56", features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Registry", "Win32_Security", "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm", "Win32_UI_Input_KeyboardAndMouse"] }
tauri-winrt-notification = "0.7"
winprint = { version = "0.2", default-features = false }

[build-dependencies]
winres = "0.1"